Завдання:

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

In [3]:
# vector_1 = np.array([i for i in range(1,11)])
vector_1 = np.arange(1,11)
print(vector_1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
matrix_zeros = np.zeros((3,3))
print(matrix_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
# start_index,matrix_name, minimal range and maximum range) 
def create_matrix(index, matrix, min_range, max_range):
    while index <= len(matrix) - 1:
        i = 0
        for i in range(len(matrix)):
            matrix[index][i] = np.random.randint(min_range,max_range+1)
        index+=1
    return matrix

In [ ]:
matrix_5 = np.zeros((5,5), dtype=int)
min_range = 1
max_range = 10
start_index = 0
matrix_5 = create_matrix(start_index, matrix_5, min_range,max_range)
print(matrix_5)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix_4 = np.random.random((4,4))
print(matrix_4)

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
vector_5 = np.array([np.random.randint(1,11) for i in range(5)])
vector_6 = np.array([np.random.randint(1,11) for i in range(5)])

print('Vector_5: ')
print(vector_5)
print('Vector_6')
print(vector_6)

#додавання
elements_sum = vector_5 + vector_6
print('додавання: ')
print(elements_sum)

elements_substraction = vector_5 - vector_6
print('віднімання: ')
print(elements_substraction)

elements_multiplication = vector_5 * vector_6
print('множення: ')
print(elements_multiplication)


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
x = 5
y = 14
vector_7 = np.array([np.random.randint(x,y) for i in range(7)])
vector_8 = np.array([np.random.randint(x,y) for i in range(7)])

print('Vector_7')
print(vector_7)

print('Vector_8')
print(vector_8)

product = np.dot(vector_7, vector_8)
print('скалярний добуток')
print(product)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix_7 = np.ones((2,2), dtype=int)
matrix_8 = np.ones((2,3), dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_7 = create_matrix(start_index, matrix_7, min_range, max_range)
matrix_8 = create_matrix(start_index, matrix_8, min_range, max_range)

print('matrix_7: ')
print(matrix_7)

print('matrix_8: ')
print(matrix_8)
        
product = np.dot(matrix_7,matrix_8)
print('Product:')
print(product)

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix_9 = np.ones((3,3), dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_9 = create_matrix(start_index, matrix_9, min_range, max_range)

print('matrix_9: ')
print(matrix_9)
if np.linalg.det(matrix_9) != 0:
    inverted_m = np.linalg.inv(matrix_9)
    print('обернена матриця:')
    print(inverted_m)
else:
    print('Матриця вироджена, оберненої не існує')

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix_10 = np.random.random((4,4))

print('matrix_10')
print(matrix_10)

transposed_m = matrix_10.T
print('Transposed matrix')
print(transposed_m)

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix_11 = np.zeros((3,4), dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_11_f = create_matrix(start_index,matrix_11,min_range,max_range)
vector_11 = np.array([np.random.randint(1,10) for i in range(4)])
print('matrix_11: ')
print(matrix_11_f)
print('vector_11: ')
print(vector_11)

product = np.dot(matrix_11,vector_11)

print('Mноження матриці на вектор')
print(product)

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix_12 = np.random.uniform(0,1, (2,3))
vector_12 = np.array([np.random.randint(1,4) for i in range(3)], dtype=float)

print('matrix_12: ')
print(matrix_12)
print('vector_12: ')
print(vector_12)

product = np.dot(matrix_12,vector_12)
print('Mноження матриці на вектор: ')
print(product)

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix_13 = np.ones((2,2), dtype=int)
matrix_14 = np.ones((2,2),dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_13 = create_matrix(start_index,matrix_13,min_range,max_range)
matrix_14 = create_matrix(start_index,matrix_14,min_range,max_range)
print('matrix_13: ')
print(matrix_13)
print('matrix_14: ')
print(matrix_14)

multiply_f = matrix_13 * matrix_14
print('множення двох матриць: ')
print(multiply_f)


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix_15 = np.zeros((2,2), dtype=int)
matrix_16 = np.zeros((2,2), dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_15 = create_matrix(start_index,matrix_15,min_range,max_range)
matrix_16 = create_matrix(start_index,matrix_16,min_range,max_range)

print('matrix_15: ')
print(matrix_15)
print('matrix_16: ')
print(matrix_16)
product = np.dot(matrix_15,matrix_16)
print('добуток: ')
print(product)

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix_17 = np.ones((5,5), dtype=int)
start_index = 0
min_range = 1
max_range = 100
matrix_17 = create_matrix(start_index,matrix_17,min_range,max_range)
print('matrix_17: ')
print(matrix_17)

sum = matrix_17.sum()
print('суму елементів матриці: ')
print(sum)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix_18 = np.ones((4,4), dtype=int)
matrix_19 = np.ones((4,4), dtype=int)
start_index = 0
min_range = 1
max_range = 10
matrix_18 = create_matrix(start_index,matrix_18,min_range,max_range)
matrix_19 = create_matrix(start_index,matrix_19,min_range,max_range)
print('matrix_18: ')
print(matrix_18)
print('matrix_19: ')
print(matrix_19)

sub_1 = matrix_18 - matrix_19
sub_2 = matrix_19 - matrix_18
print('різниця між 18 та 19: ')
print(sub_1)
print('різниця між 19 та 18: ')
print(sub_2)

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix_20 = np.random.uniform(0,1,(3,3))
print('matrix_20: ')
print(matrix_20)

vector_20 = matrix_20.sum(axis=1).reshape(3,1)
print('vector_20: ')
print(vector_20)

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix_21 = np.random.randint(1, 21, (3, 4))

print('matrix_21: ')
print(matrix_21)
# 1-st option:
# matrix_square = matrix_21 * matrix_21
#2-nd option
matrix_square = matrix_21 ** 2
print('квадратна матриця: ')
print(matrix_square)

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector_18 = np.array([np.random.randint(1,50+1) for i in range(4)],dtype=int)
print('vector_18')
print(vector_18)
# 1-st option
#sq_root_v = vector_18 ** 0.5
# 2-nd option
sq_root_v = np.sqrt(vector_18)
print('вектор з квадратними коренями цих чисел: ')
print(sq_root_v)

Завдання 2 (додаткове, за бажанням)

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('arr:\n',arr)
i = 0
for i in range(len(arr)):
    if arr[i] % 2 != 0:
        arr[i] = -1
print(arr)

2.  Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [ ]:
vector = np.arange(1,5)
print('1D-масив: ')
print(vector)
matrix = vector.reshape((2,2))
print('2D-масив: ')
print(matrix)

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [ ]:
a = np.random.randint(1,10, (2,2))
b = np.random.randint(1,10, (2,2))
print('a matrix')
print(a)
print('b matrix')
print(b)
matrix = np.concatenate((a,b), axis=0)
print('складіть масиви a i b вертикально: ')
print(matrix)

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3])
print('a matrix')
print(a)

part_1 = np.repeat(a,len(a))
part_2 = np.tile(a,len(a))
result_m = np.concatenate((part_1,part_2))
print(result_m)

5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
print('спільні елементи між a і b')
print(c)

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50,20)
print('matrix a: ')
print(a)
sorted_a = np.sort(a)
reversed_a = np.flip(sorted_a)
print('перші 5 максимальних чисел')
print(reversed_a[0:5])

7. Вилучіть усі значення NaN із одновимірного масиву
а=np.array([1,2,3,np.nan,5,6,7,np.nan])


In [ ]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print('Array a')
print(a)

a = a[~np.isnan(a)]
print(a)

8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])
eu_d = np.linalg.norm(a-b)
print(eu_d)

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indice_1 = np.where(x==1)[0]
fifth_occurance = indice_1[4]
print('індекс 5-го повторення числа 1: ', fifth_occurance)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.
np.random.seed(100) a = np.random.randint(0, 5, 10)
[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [5]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
_, idx = np.unique(a, return_index=True)
mask = np.ones(len(a), dtype=bool)
mask[idx] = False
print('Output: ', mask)

Output:  [False  True False  True False False  True  True  True  True]
